### ISSUE TITLE
New EEP Function

### ISSUE THREAD

**Issue by night-herons** [buildersbrewery/linden-scripting-language#51] opened 2020-12-28 04:21 UTC
There is a function implemented in the new feature EEP.
These are a set of functions that allow WindLight settings to be changed dynamically from a script.
More details can be found in this forum

https://community.secondlife.com/forums/topic/432351-lsl-eep-scripting-documentation/

**Comment by buildersbrewery** [comment] 2022-11-07 23:23
duplicate of #44

**Closed as completed by buildersbrewery** 2022-11-07 23:23 UTC
